use crate::parser::ast::*;

grammar;

// 跳过空白符和注释
match {
    r"\s*" => {},
    r"//[^\n\r]*[\n\r]*" => {},
    r"/\*[\s\S]*\*/" => {},
    _
}

pub CompUnit: compunit::CompUnit = {
    <FuncDef> => compunit::CompUnit {
        items: vec![<>],
    },
}

FuncDef: item::Item = {
    <frt:FuncRetType> <id:Ident> "(" ")" <b:Block> => {
        item::Item::FuncDef(item::FuncDef {
            return_type: frt,
            ident: id,
            body: b,
        })
    }
}

FuncRetType: common::Type = {
    "int" => common::Type::Simple("int".to_string()),
}

Block: Vec<statement::Statement> = {
    "{" <Stmt> "}" => vec![<>],
}

Stmt: statement::Statement = {
    "return" <Expression> ";" => statement::Statement::Return(<>),
}

Expression: expression::Expression = {
    <AddExpression> => <>,
}

AddExpression: expression::Expression = {
    <MulExpression> => <>,
    <e1:AddExpression> "+" <e2:MulExpression>
        => expression::Expression::Binary(Box::new(e1), expression::BinaryOp::Add, Box::new(e2)),
    <e1:AddExpression> "-" <e2:MulExpression>
        => expression::Expression::Binary(Box::new(e1), expression::BinaryOp::Sub, Box::new(e2)),
}

MulExpression: expression::Expression = {
    <UnaryExpression> => <>,
    <e1:MulExpression> "*" <e2:UnaryExpression>
        => expression::Expression::Binary(Box::new(e1), expression::BinaryOp::Mul, Box::new(e2)),
    <e1:MulExpression> "/" <e2:UnaryExpression>
        => expression::Expression::Binary(Box::new(e1), expression::BinaryOp::Div, Box::new(e2)),
    <e1:MulExpression> "%" <e2:UnaryExpression>
        => expression::Expression::Binary(Box::new(e1), expression::BinaryOp::Rem, Box::new(e2)),
}

UnaryExpression: expression::Expression = {
    <PrimaryExpression> => <>,
    "+" <UnaryExpression> => expression::Expression::Unary(expression::UnaryOp::Plus, Box::new(<>)),
    "-" <UnaryExpression> => expression::Expression::Unary(expression::UnaryOp::Minus, Box::new(<>)),
    "!" <UnaryExpression> => expression::Expression::Unary(expression::UnaryOp::LogicalNot, Box::new(<>)),
}

PrimaryExpression: expression::Expression = {
    <IntLit> => expression::Expression::IntLit(<>),
    "(" <Expression> ")" => <>
}

Ident: common::Ident = {
    r"[_a-zA-Z][_a-zA-Z0-9]*" => common::Ident(<>.to_string()),
}

IntLit: i32 = {
    r"[1-9][0-9]*" => i32::from_str_radix(<>, 10).unwrap(),
    r"0[0-7]*" => i32::from_str_radix(<>, 8).unwrap(),
    r"0[xX][0-9a-fA-F]+" => i32::from_str_radix(&<>[2..], 16).unwrap(),
}
