use crate::parser::ast::*;
use std::cell::RefCell;
use uuid::*;

grammar;

// 跳过空白符和注释
match {
    r"\s*" => {},
    r"//[^\n\r]*[\n\r]*" => {},
    r"/\*[\s\S]*\*/" => {},
    _
}

pub CompileUnit: compile_unit::CompileUnit = {
    <FuncDef> => compile_unit::CompileUnit {
        items: vec![<>],
    },
}

FuncDef: item::Item = {
    <frt:FuncRetType> <id:Identifier> "(" ")" <b:Block> => {
        item::Item::FuncDef(item::FuncDef {
            return_type: frt,
            ident: id,
            body: b,
        })
    }
}

FuncRetType: common::Type = {
    "int" => common::Type::Simple("int".to_string()),
}

Block: Vec<statement::Statement> = {
    "{" <(<Stmt>)*> "}" => <>,
}

Stmt: statement::Statement = {
    <OpenedStmt> => <>,
    <ClosedStmt> => <>,
}

SimpleNonIf: statement::Statement = {
    <ConstDecl> => <>,
    <VarDecl> => <>,
    <Assign> => <>,
    "return" <Expression> ";" => statement::Statement::Return(<>),
    ";" => statement::Statement::Expression(None),
    <Expression> ";" => statement::Statement::Expression(Some(<>)),
    <Block> => {
        let v: Vec<Box<_>> = <>.iter().map(|s| Box::new(s.clone())).collect();
        statement::Statement::Block(v)
    },
    "break" ";" => statement::Statement::Break,
    "continue" ";" => statement::Statement::Continue,
}

ConstDecl: statement::Statement = {
    "const" <ty:Type> <first:ConstDef> <rest:("," <ConstDef>)*> ";" => {
        let mut v = vec![first];
        v.extend(rest);
        let v: Vec<(common::Type, common::Identifier, expression::Expression)>
            = v.iter().map(|elem| (ty.clone(), elem.0.clone(), elem.1.clone())).collect();
        statement::Statement::ConstDecl(v)
    }
}

ConstDef: (common::Identifier, expression::Expression) = {
    <id:Identifier> "=" <e:Expression> => (id, e),
}

VarDecl: statement::Statement = {
    <ty:Type> <first:VarDef> <rest:("," <VarDef>)*> ";" => {
        let mut v = vec![first];
        v.extend(rest);
        let v: Vec<(common::Type, common::Identifier, Option<expression::Expression>)>
            = v.iter().map(|elem| (ty.clone(), elem.0.clone(), elem.1.clone())).collect();
        statement::Statement::VarDecl(v)
    }
}

VarDef: (common::Identifier, Option<expression::Expression>) = {
    <id:Identifier> => (id, None),
    <id:Identifier> "=" <e:Expression> => (id, Some(e)),
}

Assign: statement::Statement = {
    <id:Identifier> "=" <e:Expression> ";" => statement::Statement::Assign(id, e)
}

ClosedStmt: statement::Statement = {
    "if" "(" <guard:Expression> ")" <then_branch:ClosedStmt> "else" <else_branch:ClosedStmt> =>
        statement::Statement::If(guard, Box::new(then_branch), Some(Box::new(else_branch))),
    "while" "(" <e:Expression> ")" <s:ClosedStmt> => statement::Statement::While(e, Box::new(s)),
    <SimpleNonIf> => <>,
}

OpenedStmt: statement::Statement = {
    "if" "(" <guard:Expression> ")" <then_branch:Stmt> =>
        statement::Statement::If(guard, Box::new(then_branch), None),
    "if" "(" <guard:Expression> ")" <then_branch:ClosedStmt> "else" <else_branch:OpenedStmt> =>
        statement::Statement::If(guard, Box::new(then_branch), Some(Box::new(else_branch))),
    "while" "(" <e:Expression> ")" <s:OpenedStmt> => statement::Statement::While(e, Box::new(s)),
}

Expression: expression::Expression = {
    <LogicalOrExpression> => <>,
}

LogicalOrExpression: expression::Expression = {
    <LogicalAndExpression> => <>,
    <e1:LogicalOrExpression> "||" <e2:LogicalAndExpression>
        => expression::Expression::Binary(Box::new(e1), expression::BinaryOp::LogicalOr, Box::new(e2)),
}

LogicalAndExpression: expression::Expression = {
    <EqExpression> => <>,
    <e1:LogicalAndExpression> "&&" <e2:EqExpression>
        => expression::Expression::Binary(Box::new(e1), expression::BinaryOp::LogicalAnd, Box::new(e2)),
}

EqExpression: expression::Expression = {
    <RelationalExpression> => <>,
    <e1:EqExpression> "==" <e2:RelationalExpression>
        => expression::Expression::Binary(Box::new(e1), expression::BinaryOp::Eq, Box::new(e2)),
    <e1:EqExpression> "!=" <e2:RelationalExpression>
        => expression::Expression::Binary(Box::new(e1), expression::BinaryOp::NotEq, Box::new(e2)),
}

RelationalExpression: expression::Expression = {
    <AddExpression> => <>,
    <e1:RelationalExpression> "<" <e2:AddExpression>
        => expression::Expression::Binary(Box::new(e1), expression::BinaryOp::Less, Box::new(e2)),
    <e1:RelationalExpression> "<=" <e2:AddExpression>
        => expression::Expression::Binary(Box::new(e1), expression::BinaryOp::Le, Box::new(e2)),
    <e1:RelationalExpression> ">=" <e2:AddExpression>
        => expression::Expression::Binary(Box::new(e1), expression::BinaryOp::Ge, Box::new(e2)),
    <e1:RelationalExpression> ">" <e2:AddExpression>
        => expression::Expression::Binary(Box::new(e1), expression::BinaryOp::Greater, Box::new(e2)),

}

AddExpression: expression::Expression = {
    <MulExpression> => <>,
    <e1:AddExpression> "+" <e2:MulExpression>
        => expression::Expression::Binary(Box::new(e1), expression::BinaryOp::Add, Box::new(e2)),
    <e1:AddExpression> "-" <e2:MulExpression>
        => expression::Expression::Binary(Box::new(e1), expression::BinaryOp::Sub, Box::new(e2)),
}

MulExpression: expression::Expression = {
    <UnaryExpression> => <>,
    <e1:MulExpression> "*" <e2:UnaryExpression>
        => expression::Expression::Binary(Box::new(e1), expression::BinaryOp::Mul, Box::new(e2)),
    <e1:MulExpression> "/" <e2:UnaryExpression>
        => expression::Expression::Binary(Box::new(e1), expression::BinaryOp::Div, Box::new(e2)),
    <e1:MulExpression> "%" <e2:UnaryExpression>
        => expression::Expression::Binary(Box::new(e1), expression::BinaryOp::Rem, Box::new(e2)),
}

UnaryExpression: expression::Expression = {
    <PrimaryExpression> => <>,
    "+" <UnaryExpression> => expression::Expression::Unary(expression::UnaryOp::Plus, Box::new(<>)),
    "-" <UnaryExpression> => expression::Expression::Unary(expression::UnaryOp::Minus, Box::new(<>)),
    "!" <UnaryExpression> => expression::Expression::Unary(expression::UnaryOp::LogicalNot, Box::new(<>)),
}

PrimaryExpression: expression::Expression = {
    <IntLit> => expression::Expression::IntLit(<>),
    <Identifier> => expression::Expression::Ident(<>),
    "(" <Expression> ")" => <>
}

Type: common::Type = {
    "int" => common::Type::Simple("int".to_string()),
}

Identifier: common::Identifier = {
    r"[_a-zA-Z][_a-zA-Z0-9]*" => common::Identifier {
        name: <>.to_string(),
        resolve_status: RefCell::new(common::ResolveStatus::Unresolved),
        uuid: Uuid::new_v4(),
    },
}

IntLit: i32 = {
    r"[1-9][0-9]*" => i32::from_str_radix(<>, 10).unwrap(),
    r"0[0-7]*" => i32::from_str_radix(<>, 8).unwrap(),
    r"0[xX][0-9a-fA-F]+" => i32::from_str_radix(&<>[2..], 16).unwrap(),
}
